function ok = Matrix2csv(cfg)
% MATRIX2CSV  Convert Matrix .mat files to .csv with column headers.
% Fully automated: no GUI. Uses config with Category -> File Type paths.
%
% cfg.categoryRoot, cfg.categoryName.
% Reads: Matrix/*.mat. Writes: Matrix_CSV/*.csv.

ok = false;
if nargin < 1 || ~isstruct(cfg)
    error('Matrix2csv requires config struct cfg with categoryRoot, categoryName.');
end

paths = pipeline_getCategoryPaths(cfg.categoryRoot, cfg.categoryName);
inputDir = paths.Matrix;
outputDir = paths.Matrix_CSV;

if ~exist(inputDir, 'dir')
    error('Matrix directory does not exist: %s', inputDir);
end
if ~exist(outputDir, 'dir'), mkdir(outputDir); end

matFiles = dir(fullfile(inputDir, '*.mat'));
if isempty(matFiles)
    fprintf('No .mat files in %s. Skipping.\n', inputDir);
    ok = true;
    return;
end

columnNames = {'Unique id','Total previous reviews within 0 days','Total previous reviews within 1 days','Total previous reviews within 2 days',...
    'Total previous reviews within 3 days','Total previous reviews within 4 days','Total previous reviews within 5 days',...
    'Total previous reviews within 6 days','Total previous reviews within 7 days',...
    'Total previous rating 1 within a 0-day window','Total previous rating 2 within a 0-day window','Total previous rating 3 within a 0-day window'...
    'Total previous rating 4 within a 0-day window','Total previous  rating 5 within a 0-day window',...
    'rating Avg 0 days window', 'rating std 0 days window', 'attractors % 0 days window', 'detractors % 0 days window'...
    'Total previous rating 1 within a 1-day window','Total previous rating 2 within a 1-day window','Total previous rating 3 within a 1-day window'...
    'Total previous rating 4 within a 1-day window','Total previous  rating 5 within a 1-day window',...
    'rating Avg 1 days window', 'rating std 1 days window', 'attractors % 1 days window', 'detractors % 1 days window'...
    'Total previous rating 1 within a 2-day window','Total previous rating 2 within a 2-day window','Total previous rating 3 within a 2-day window'...
    'Total previous rating 4 within a 2-day window','Total previous  rating 5 within a 2-day window',...
    'rating Avg 2 days window', 'rating std 2 days window', 'attractors % 2 days window', 'detractors % 2 days window'...
    'Total previous rating 1 within a 3-day window','Total previous rating 2 within a 3-day window','Total previous rating 3 within a 3-day window'...
    'Total previous rating 4 within a 3-day window','Total previous  rating 5 within a 3-day window',...
    'rating Avg 3 days window', 'rating std 3 days window', 'attractors % 3 days window', 'detractors % 3 days window'...
    'Total previous rating 1 within a 4-day window','Total previous rating 2 within a 4-day window','Total previous rating 3 within a 4-day window'...
    'Total previous rating 4 within a 4-day window','Total previous  rating 5 within a 4-day window',...
    'rating Avg 4 days window', 'rating std 4 days window', 'attractors % 4 days window', 'detractors % 4 days window'...
    'Total previous rating 1 within a 5-day window','Total previous rating 2 within a 5-day window','Total previous rating 3 within a 5-day window'...
    'Total previous rating 4 within a 5-day window','Total previous  rating 5 within a 5-day window',...
    'rating Avg 5 days window', 'rating std 5 days window', 'attractors % 5 days window', 'detractors % 5 days window'...
    'Total previous rating 1 within a 6-day window','Total previous rating 2 within a 6-day window','Total previous rating 3 within a 6-day window'...
    'Total previous rating 4 within a 6-day window','Total previous  rating 5 within a 6-day window',...
    'rating Avg 6 days window', 'rating std 6 days window', 'attractors % 6 days window', 'detractors % 6 days window'...
    'Total previous rating 1 within a 7-day window','Total previous rating 2 within a 7-day window','Total previous rating 3 within a 7-day window'...
    'Total previous rating 4 within a 7-day window','Total previous  rating 5 within a 7-day window',...
    'rating Avg 7 days window', 'rating std 7 days window', 'attractors % 7 days window', 'detractors % 7 days window'...
    'days since first review', 'reviews delta time', 'delta time OutOf 1 dayWindow', 'delta time OutOf 2 dayWindow',...
    'delta time OutOf 3 dayWindow', 'delta time OutOf 4 dayWindow', 'delta time OutOf 5 dayWindow', 'delta time OutOf 6 dayWindow', ...
    'delta time OutOf 7 dayWindow', 'rating', 'verified purchases', 'helpful votes','text_size', 'year', 'mounth', 'day', 'weekday',...
    'is censored?', 'consored row', 'total num of reviews', 'launch year'
};

for i = 1:length(matFiles)
    matFilePath = fullfile(inputDir, matFiles(i).name);
    fprintf('Processing: %s\n', matFilePath);

    dataStruct = load(matFilePath);
    fieldNames = fieldnames(dataStruct);
    mainData = dataStruct.(fieldNames{1});

    [~, name, ~] = fileparts(matFiles(i).name);
    csvFileName = fullfile(outputDir, [name, '.csv']);
    writecell(columnNames, csvFileName);
    writematrix(mainData, csvFileName, 'WriteMode', 'append');
    fprintf('Saved CSV: %s\n', csvFileName);
end

fprintf('Conversion complete. All CSV files in: %s\n', outputDir);
ok = true;
end
