%% script to convert Matrix .mat fiels to .csv files
% Prompt user to select the input directory containing .mat files
clear;
inputDir = uigetdir('', 'Select the folder containing .mat files');
outputDir = 'F:\AmazonData_Part1Full\Categories\Automotive\Matrix_CSV';
if inputDir == 0
    error('No directory selected. Exiting script.');
end

% Get a list of all .mat files in the directory
matFiles = dir(fullfile(inputDir, '*.mat'));

% Define output directory (same as input or create a "CSV_Output" folder)
% outputDir = fullfile(outputDir, 'Matrix_CSV','Home_and_Kitchen');
% if ~exist(outputDir, 'dir')
%     mkdir(outputDir);
% end

columnNames = {'Unique id','Total previous reviews within 0 days','Total previous reviews within 1 days','Total previous reviews within 2 days',...
    'Total previous reviews within 3 days','Total previous reviews within 4 days','Total previous reviews within 5 days',...
    'Total previous reviews within 6 days','Total previous reviews within 7 days',...
    'Total previous rating 1 within a 0-day window','Total previous rating 2 within a 0-day window','Total previous rating 3 within a 0-day window'...
    'Total previous rating 4 within a 0-day window','Total previous  rating 5 within a 0-day window',...
    'rating Avg 0 days window', 'rating std 0 days window', 'attractors % 0 days window', 'detractors % 0 days window'...
    'Total previous rating 1 within a 1-day window','Total previous rating 2 within a 1-day window','Total previous rating 3 within a 1-day window'...
    'Total previous rating 4 within a 1-day window','Total previous  rating 5 within a 1-day window',...
    'rating Avg 1 days window', 'rating std 1 days window', 'attractors % 1 days window', 'detractors % 1 days window'...
    'Total previous rating 1 within a 2-day window','Total previous rating 2 within a 2-day window','Total previous rating 3 within a 2-day window'...
    'Total previous rating 4 within a 2-day window','Total previous  rating 5 within a 2-day window',...
    'rating Avg 2 days window', 'rating std 2 days window', 'attractors % 2 days window', 'detractors % 2 days window'...
    'Total previous rating 1 within a 3-day window','Total previous rating 2 within a 3-day window','Total previous rating 3 within a 3-day window'...
    'Total previous rating 4 within a 3-day window','Total previous  rating 5 within a 3-day window',...
    'rating Avg 3 days window', 'rating std 3 days window', 'attractors % 3 days window', 'detractors % 3 days window'...
    'Total previous rating 1 within a 4-day window','Total previous rating 2 within a 4-day window','Total previous rating 3 within a 4-day window'...
    'Total previous rating 4 within a 4-day window','Total previous  rating 5 within a 4-day window',...
    'rating Avg 4 days window', 'rating std 4 days window', 'attractors % 4 days window', 'detractors % 4 days window'...
    'Total previous rating 1 within a 5-day window','Total previous rating 2 within a 5-day window','Total previous rating 3 within a 5-day window'...
    'Total previous rating 4 within a 5-day window','Total previous  rating 5 within a 5-day window',...
    'rating Avg 5 days window', 'rating std 5 days window', 'attractors % 5 days window', 'detractors % 5 days window'...
    'Total previous rating 1 within a 6-day window','Total previous rating 2 within a 6-day window','Total previous rating 3 within a 6-day window'...
    'Total previous rating 4 within a 6-day window','Total previous  rating 5 within a 6-day window',...
    'rating Avg 6 days window', 'rating std 6 days window', 'attractors % 6 days window', 'detractors % 6 days window'...
    'Total previous rating 1 within a 7-day window','Total previous rating 2 within a 7-day window','Total previous rating 3 within a 7-day window'...
    'Total previous rating 4 within a 7-day window','Total previous  rating 5 within a 7-day window',...
    'rating Avg 7 days window', 'rating std 7 days window', 'attractors % 7 days window', 'detractors % 7 days window'...
    'days since first review', 'reviews delta time', 'delta time OutOf 1 dayWindow', 'delta time OutOf 2 dayWindow',...
    'delta time OutOf 3 dayWindow', 'delta time OutOf 4 dayWindow', 'delta time OutOf 5 dayWindow', 'delta time OutOf 6 dayWindow', ...
    'delta time OutOf 7 dayWindow', 'rating', 'verified purchases', 'helpful votes','text_size', 'year', 'mounth', 'day', 'weekday',...
    'is censored?', 'consored row', 'total num of reviews', 'launch year'
    };

% Process each .mat file
for i = 1:length(matFiles)
    % Construct full file path
    matFilePath = fullfile(inputDir, matFiles(i).name);
    fprintf('Processing: %s\n', matFilePath);
    
    % Load .mat file data
    dataStruct = load(matFilePath);
    
    % Extract the first (and only) field, assuming it's a table
    fieldNames = fieldnames(dataStruct);
    mainData = dataStruct.(fieldNames{1});
    

    % Construct CSV filename (same name as .mat but with .csv extension)
    [~, name, ~] = fileparts(matFiles(i).name);
    csvFileName = fullfile(outputDir, [name, '.csv']);

    % Write column headers first
    writecell(columnNames, csvFileName);

    % Write table to CSV with column headers
    writematrix(mainData, csvFileName,'WriteMode', 'append');

    fprintf('Saved CSV: %s\n', csvFileName);
end

fprintf('Conversion complete. All CSV files are in: %s\n', outputDir);
